
language: swift

matrix:
    include:
        - os: osx
          osx_image: xcode9
          script:
            - swift package update
            - swift package tools-version --set-current
            - swift test
notifications:
    email:
        on_success: never
        on_failure: change