
language: swift

matrix:
    include:
        - os: osx
          osx_image: xcode8.2
          script:
            - swift package update
            - swift build
            - swift test
        - os: linux
          dist: trusty
          sudo: required
          before_install:
            - git clone https://github.com/IBM-Swift/Package-Builder.git
          script:
            - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
notifications:
    email:
        on_success: never
        on_failure: change