
matrix:
    include:
        - os: osx
          osx_image: xcode8.3
          language: swift
          script:
            - swift package update
            - swift build
            - swift test
notifications:
    email:
        on_success: never
        on_failure: change