//
// GLMath - Swizzle.swift
//
// Copyright (c) 2016 The GLMath authors.
// Licensed under MIT License.

// NOTE:
// - Do NOT edit this file. Edit `Swizzle.swift.gyb` file instead.
// - Combinations of `s, t, u, v` are not implemented.

// TODO: Swizzle properties shall be settable.

public extension Vector2 {

    var r: Component { return self.x }
    var g: Component { return self.y }

    var yy: Self { return Self(self.y, self.y) }
    var yx: Self { return Self(self.y, self.x) }
    var xy: Self { return Self(self.x, self.y) }
    var xx: Self { return Self(self.x, self.x) }
    var rr: Self { return Self(self.r, self.r) }
    var rg: Self { return Self(self.r, self.g) }
    var gr: Self { return Self(self.g, self.r) }
    var gg: Self { return Self(self.g, self.g) }
}

public extension Vector3 {
    var r: Component { return self.x }
    var g: Component { return self.y }
    var b: Component { return self.z }

    var yy: AssociatedVector2 { return AssociatedVector2(self.y, self.y) }
    var yx: AssociatedVector2 { return AssociatedVector2(self.y, self.x) }
    var yz: AssociatedVector2 { return AssociatedVector2(self.y, self.z) }
    var xy: AssociatedVector2 { return AssociatedVector2(self.x, self.y) }
    var xx: AssociatedVector2 { return AssociatedVector2(self.x, self.x) }
    var xz: AssociatedVector2 { return AssociatedVector2(self.x, self.z) }
    var zy: AssociatedVector2 { return AssociatedVector2(self.z, self.y) }
    var zx: AssociatedVector2 { return AssociatedVector2(self.z, self.x) }
    var zz: AssociatedVector2 { return AssociatedVector2(self.z, self.z) }
    var yyy: Self { return Self(self.y, self.y, self.y) }
    var yyx: Self { return Self(self.y, self.y, self.x) }
    var yyz: Self { return Self(self.y, self.y, self.z) }
    var yxy: Self { return Self(self.y, self.x, self.y) }
    var yxx: Self { return Self(self.y, self.x, self.x) }
    var yxz: Self { return Self(self.y, self.x, self.z) }
    var yzy: Self { return Self(self.y, self.z, self.y) }
    var yzx: Self { return Self(self.y, self.z, self.x) }
    var yzz: Self { return Self(self.y, self.z, self.z) }
    var xyy: Self { return Self(self.x, self.y, self.y) }
    var xyx: Self { return Self(self.x, self.y, self.x) }
    var xyz: Self { return Self(self.x, self.y, self.z) }
    var xxy: Self { return Self(self.x, self.x, self.y) }
    var xxx: Self { return Self(self.x, self.x, self.x) }
    var xxz: Self { return Self(self.x, self.x, self.z) }
    var xzy: Self { return Self(self.x, self.z, self.y) }
    var xzx: Self { return Self(self.x, self.z, self.x) }
    var xzz: Self { return Self(self.x, self.z, self.z) }
    var zyy: Self { return Self(self.z, self.y, self.y) }
    var zyx: Self { return Self(self.z, self.y, self.x) }
    var zyz: Self { return Self(self.z, self.y, self.z) }
    var zxy: Self { return Self(self.z, self.x, self.y) }
    var zxx: Self { return Self(self.z, self.x, self.x) }
    var zxz: Self { return Self(self.z, self.x, self.z) }
    var zzy: Self { return Self(self.z, self.z, self.y) }
    var zzx: Self { return Self(self.z, self.z, self.x) }
    var zzz: Self { return Self(self.z, self.z, self.z) }
    var rr: AssociatedVector2 { return AssociatedVector2(self.r, self.r) }
    var rb: AssociatedVector2 { return AssociatedVector2(self.r, self.b) }
    var rg: AssociatedVector2 { return AssociatedVector2(self.r, self.g) }
    var br: AssociatedVector2 { return AssociatedVector2(self.b, self.r) }
    var bb: AssociatedVector2 { return AssociatedVector2(self.b, self.b) }
    var bg: AssociatedVector2 { return AssociatedVector2(self.b, self.g) }
    var gr: AssociatedVector2 { return AssociatedVector2(self.g, self.r) }
    var gb: AssociatedVector2 { return AssociatedVector2(self.g, self.b) }
    var gg: AssociatedVector2 { return AssociatedVector2(self.g, self.g) }
    var rrr: Self { return Self(self.r, self.r, self.r) }
    var rrb: Self { return Self(self.r, self.r, self.b) }
    var rrg: Self { return Self(self.r, self.r, self.g) }
    var rbr: Self { return Self(self.r, self.b, self.r) }
    var rbb: Self { return Self(self.r, self.b, self.b) }
    var rbg: Self { return Self(self.r, self.b, self.g) }
    var rgr: Self { return Self(self.r, self.g, self.r) }
    var rgb: Self { return Self(self.r, self.g, self.b) }
    var rgg: Self { return Self(self.r, self.g, self.g) }
    var brr: Self { return Self(self.b, self.r, self.r) }
    var brb: Self { return Self(self.b, self.r, self.b) }
    var brg: Self { return Self(self.b, self.r, self.g) }
    var bbr: Self { return Self(self.b, self.b, self.r) }
    var bbb: Self { return Self(self.b, self.b, self.b) }
    var bbg: Self { return Self(self.b, self.b, self.g) }
    var bgr: Self { return Self(self.b, self.g, self.r) }
    var bgb: Self { return Self(self.b, self.g, self.b) }
    var bgg: Self { return Self(self.b, self.g, self.g) }
    var grr: Self { return Self(self.g, self.r, self.r) }
    var grb: Self { return Self(self.g, self.r, self.b) }
    var grg: Self { return Self(self.g, self.r, self.g) }
    var gbr: Self { return Self(self.g, self.b, self.r) }
    var gbb: Self { return Self(self.g, self.b, self.b) }
    var gbg: Self { return Self(self.g, self.b, self.g) }
    var ggr: Self { return Self(self.g, self.g, self.r) }
    var ggb: Self { return Self(self.g, self.g, self.b) }
    var ggg: Self { return Self(self.g, self.g, self.g) }
}

public extension Vector4 {
    var r: Component { return self.x }
    var g: Component { return self.y }
    var b: Component { return self.z }
    var a: Component { return self.w }

    var yy: AssociatedVector2 { return AssociatedVector2(self.y, self.y) }
    var yx: AssociatedVector2 { return AssociatedVector2(self.y, self.x) }
    var yz: AssociatedVector2 { return AssociatedVector2(self.y, self.z) }
    var yw: AssociatedVector2 { return AssociatedVector2(self.y, self.w) }
    var xy: AssociatedVector2 { return AssociatedVector2(self.x, self.y) }
    var xx: AssociatedVector2 { return AssociatedVector2(self.x, self.x) }
    var xz: AssociatedVector2 { return AssociatedVector2(self.x, self.z) }
    var xw: AssociatedVector2 { return AssociatedVector2(self.x, self.w) }
    var zy: AssociatedVector2 { return AssociatedVector2(self.z, self.y) }
    var zx: AssociatedVector2 { return AssociatedVector2(self.z, self.x) }
    var zz: AssociatedVector2 { return AssociatedVector2(self.z, self.z) }
    var zw: AssociatedVector2 { return AssociatedVector2(self.z, self.w) }
    var wy: AssociatedVector2 { return AssociatedVector2(self.w, self.y) }
    var wx: AssociatedVector2 { return AssociatedVector2(self.w, self.x) }
    var wz: AssociatedVector2 { return AssociatedVector2(self.w, self.z) }
    var ww: AssociatedVector2 { return AssociatedVector2(self.w, self.w) }
    var yyy: AssociatedVector3 { return AssociatedVector3(self.y, self.y, self.y) }
    var yyx: AssociatedVector3 { return AssociatedVector3(self.y, self.y, self.x) }
    var yyz: AssociatedVector3 { return AssociatedVector3(self.y, self.y, self.z) }
    var yyw: AssociatedVector3 { return AssociatedVector3(self.y, self.y, self.w) }
    var yxy: AssociatedVector3 { return AssociatedVector3(self.y, self.x, self.y) }
    var yxx: AssociatedVector3 { return AssociatedVector3(self.y, self.x, self.x) }
    var yxz: AssociatedVector3 { return AssociatedVector3(self.y, self.x, self.z) }
    var yxw: AssociatedVector3 { return AssociatedVector3(self.y, self.x, self.w) }
    var yzy: AssociatedVector3 { return AssociatedVector3(self.y, self.z, self.y) }
    var yzx: AssociatedVector3 { return AssociatedVector3(self.y, self.z, self.x) }
    var yzz: AssociatedVector3 { return AssociatedVector3(self.y, self.z, self.z) }
    var yzw: AssociatedVector3 { return AssociatedVector3(self.y, self.z, self.w) }
    var ywy: AssociatedVector3 { return AssociatedVector3(self.y, self.w, self.y) }
    var ywx: AssociatedVector3 { return AssociatedVector3(self.y, self.w, self.x) }
    var ywz: AssociatedVector3 { return AssociatedVector3(self.y, self.w, self.z) }
    var yww: AssociatedVector3 { return AssociatedVector3(self.y, self.w, self.w) }
    var xyy: AssociatedVector3 { return AssociatedVector3(self.x, self.y, self.y) }
    var xyx: AssociatedVector3 { return AssociatedVector3(self.x, self.y, self.x) }
    var xyz: AssociatedVector3 { return AssociatedVector3(self.x, self.y, self.z) }
    var xyw: AssociatedVector3 { return AssociatedVector3(self.x, self.y, self.w) }
    var xxy: AssociatedVector3 { return AssociatedVector3(self.x, self.x, self.y) }
    var xxx: AssociatedVector3 { return AssociatedVector3(self.x, self.x, self.x) }
    var xxz: AssociatedVector3 { return AssociatedVector3(self.x, self.x, self.z) }
    var xxw: AssociatedVector3 { return AssociatedVector3(self.x, self.x, self.w) }
    var xzy: AssociatedVector3 { return AssociatedVector3(self.x, self.z, self.y) }
    var xzx: AssociatedVector3 { return AssociatedVector3(self.x, self.z, self.x) }
    var xzz: AssociatedVector3 { return AssociatedVector3(self.x, self.z, self.z) }
    var xzw: AssociatedVector3 { return AssociatedVector3(self.x, self.z, self.w) }
    var xwy: AssociatedVector3 { return AssociatedVector3(self.x, self.w, self.y) }
    var xwx: AssociatedVector3 { return AssociatedVector3(self.x, self.w, self.x) }
    var xwz: AssociatedVector3 { return AssociatedVector3(self.x, self.w, self.z) }
    var xww: AssociatedVector3 { return AssociatedVector3(self.x, self.w, self.w) }
    var zyy: AssociatedVector3 { return AssociatedVector3(self.z, self.y, self.y) }
    var zyx: AssociatedVector3 { return AssociatedVector3(self.z, self.y, self.x) }
    var zyz: AssociatedVector3 { return AssociatedVector3(self.z, self.y, self.z) }
    var zyw: AssociatedVector3 { return AssociatedVector3(self.z, self.y, self.w) }
    var zxy: AssociatedVector3 { return AssociatedVector3(self.z, self.x, self.y) }
    var zxx: AssociatedVector3 { return AssociatedVector3(self.z, self.x, self.x) }
    var zxz: AssociatedVector3 { return AssociatedVector3(self.z, self.x, self.z) }
    var zxw: AssociatedVector3 { return AssociatedVector3(self.z, self.x, self.w) }
    var zzy: AssociatedVector3 { return AssociatedVector3(self.z, self.z, self.y) }
    var zzx: AssociatedVector3 { return AssociatedVector3(self.z, self.z, self.x) }
    var zzz: AssociatedVector3 { return AssociatedVector3(self.z, self.z, self.z) }
    var zzw: AssociatedVector3 { return AssociatedVector3(self.z, self.z, self.w) }
    var zwy: AssociatedVector3 { return AssociatedVector3(self.z, self.w, self.y) }
    var zwx: AssociatedVector3 { return AssociatedVector3(self.z, self.w, self.x) }
    var zwz: AssociatedVector3 { return AssociatedVector3(self.z, self.w, self.z) }
    var zww: AssociatedVector3 { return AssociatedVector3(self.z, self.w, self.w) }
    var wyy: AssociatedVector3 { return AssociatedVector3(self.w, self.y, self.y) }
    var wyx: AssociatedVector3 { return AssociatedVector3(self.w, self.y, self.x) }
    var wyz: AssociatedVector3 { return AssociatedVector3(self.w, self.y, self.z) }
    var wyw: AssociatedVector3 { return AssociatedVector3(self.w, self.y, self.w) }
    var wxy: AssociatedVector3 { return AssociatedVector3(self.w, self.x, self.y) }
    var wxx: AssociatedVector3 { return AssociatedVector3(self.w, self.x, self.x) }
    var wxz: AssociatedVector3 { return AssociatedVector3(self.w, self.x, self.z) }
    var wxw: AssociatedVector3 { return AssociatedVector3(self.w, self.x, self.w) }
    var wzy: AssociatedVector3 { return AssociatedVector3(self.w, self.z, self.y) }
    var wzx: AssociatedVector3 { return AssociatedVector3(self.w, self.z, self.x) }
    var wzz: AssociatedVector3 { return AssociatedVector3(self.w, self.z, self.z) }
    var wzw: AssociatedVector3 { return AssociatedVector3(self.w, self.z, self.w) }
    var wwy: AssociatedVector3 { return AssociatedVector3(self.w, self.w, self.y) }
    var wwx: AssociatedVector3 { return AssociatedVector3(self.w, self.w, self.x) }
    var wwz: AssociatedVector3 { return AssociatedVector3(self.w, self.w, self.z) }
    var www: AssociatedVector3 { return AssociatedVector3(self.w, self.w, self.w) }
    var yyyy: Self { return Self(self.y, self.y, self.y, self.y) }
    var yyyx: Self { return Self(self.y, self.y, self.y, self.x) }
    var yyyz: Self { return Self(self.y, self.y, self.y, self.z) }
    var yyyw: Self { return Self(self.y, self.y, self.y, self.w) }
    var yyxy: Self { return Self(self.y, self.y, self.x, self.y) }
    var yyxx: Self { return Self(self.y, self.y, self.x, self.x) }
    var yyxz: Self { return Self(self.y, self.y, self.x, self.z) }
    var yyxw: Self { return Self(self.y, self.y, self.x, self.w) }
    var yyzy: Self { return Self(self.y, self.y, self.z, self.y) }
    var yyzx: Self { return Self(self.y, self.y, self.z, self.x) }
    var yyzz: Self { return Self(self.y, self.y, self.z, self.z) }
    var yyzw: Self { return Self(self.y, self.y, self.z, self.w) }
    var yywy: Self { return Self(self.y, self.y, self.w, self.y) }
    var yywx: Self { return Self(self.y, self.y, self.w, self.x) }
    var yywz: Self { return Self(self.y, self.y, self.w, self.z) }
    var yyww: Self { return Self(self.y, self.y, self.w, self.w) }
    var yxyy: Self { return Self(self.y, self.x, self.y, self.y) }
    var yxyx: Self { return Self(self.y, self.x, self.y, self.x) }
    var yxyz: Self { return Self(self.y, self.x, self.y, self.z) }
    var yxyw: Self { return Self(self.y, self.x, self.y, self.w) }
    var yxxy: Self { return Self(self.y, self.x, self.x, self.y) }
    var yxxx: Self { return Self(self.y, self.x, self.x, self.x) }
    var yxxz: Self { return Self(self.y, self.x, self.x, self.z) }
    var yxxw: Self { return Self(self.y, self.x, self.x, self.w) }
    var yxzy: Self { return Self(self.y, self.x, self.z, self.y) }
    var yxzx: Self { return Self(self.y, self.x, self.z, self.x) }
    var yxzz: Self { return Self(self.y, self.x, self.z, self.z) }
    var yxzw: Self { return Self(self.y, self.x, self.z, self.w) }
    var yxwy: Self { return Self(self.y, self.x, self.w, self.y) }
    var yxwx: Self { return Self(self.y, self.x, self.w, self.x) }
    var yxwz: Self { return Self(self.y, self.x, self.w, self.z) }
    var yxww: Self { return Self(self.y, self.x, self.w, self.w) }
    var yzyy: Self { return Self(self.y, self.z, self.y, self.y) }
    var yzyx: Self { return Self(self.y, self.z, self.y, self.x) }
    var yzyz: Self { return Self(self.y, self.z, self.y, self.z) }
    var yzyw: Self { return Self(self.y, self.z, self.y, self.w) }
    var yzxy: Self { return Self(self.y, self.z, self.x, self.y) }
    var yzxx: Self { return Self(self.y, self.z, self.x, self.x) }
    var yzxz: Self { return Self(self.y, self.z, self.x, self.z) }
    var yzxw: Self { return Self(self.y, self.z, self.x, self.w) }
    var yzzy: Self { return Self(self.y, self.z, self.z, self.y) }
    var yzzx: Self { return Self(self.y, self.z, self.z, self.x) }
    var yzzz: Self { return Self(self.y, self.z, self.z, self.z) }
    var yzzw: Self { return Self(self.y, self.z, self.z, self.w) }
    var yzwy: Self { return Self(self.y, self.z, self.w, self.y) }
    var yzwx: Self { return Self(self.y, self.z, self.w, self.x) }
    var yzwz: Self { return Self(self.y, self.z, self.w, self.z) }
    var yzww: Self { return Self(self.y, self.z, self.w, self.w) }
    var ywyy: Self { return Self(self.y, self.w, self.y, self.y) }
    var ywyx: Self { return Self(self.y, self.w, self.y, self.x) }
    var ywyz: Self { return Self(self.y, self.w, self.y, self.z) }
    var ywyw: Self { return Self(self.y, self.w, self.y, self.w) }
    var ywxy: Self { return Self(self.y, self.w, self.x, self.y) }
    var ywxx: Self { return Self(self.y, self.w, self.x, self.x) }
    var ywxz: Self { return Self(self.y, self.w, self.x, self.z) }
    var ywxw: Self { return Self(self.y, self.w, self.x, self.w) }
    var ywzy: Self { return Self(self.y, self.w, self.z, self.y) }
    var ywzx: Self { return Self(self.y, self.w, self.z, self.x) }
    var ywzz: Self { return Self(self.y, self.w, self.z, self.z) }
    var ywzw: Self { return Self(self.y, self.w, self.z, self.w) }
    var ywwy: Self { return Self(self.y, self.w, self.w, self.y) }
    var ywwx: Self { return Self(self.y, self.w, self.w, self.x) }
    var ywwz: Self { return Self(self.y, self.w, self.w, self.z) }
    var ywww: Self { return Self(self.y, self.w, self.w, self.w) }
    var xyyy: Self { return Self(self.x, self.y, self.y, self.y) }
    var xyyx: Self { return Self(self.x, self.y, self.y, self.x) }
    var xyyz: Self { return Self(self.x, self.y, self.y, self.z) }
    var xyyw: Self { return Self(self.x, self.y, self.y, self.w) }
    var xyxy: Self { return Self(self.x, self.y, self.x, self.y) }
    var xyxx: Self { return Self(self.x, self.y, self.x, self.x) }
    var xyxz: Self { return Self(self.x, self.y, self.x, self.z) }
    var xyxw: Self { return Self(self.x, self.y, self.x, self.w) }
    var xyzy: Self { return Self(self.x, self.y, self.z, self.y) }
    var xyzx: Self { return Self(self.x, self.y, self.z, self.x) }
    var xyzz: Self { return Self(self.x, self.y, self.z, self.z) }
    var xyzw: Self { return Self(self.x, self.y, self.z, self.w) }
    var xywy: Self { return Self(self.x, self.y, self.w, self.y) }
    var xywx: Self { return Self(self.x, self.y, self.w, self.x) }
    var xywz: Self { return Self(self.x, self.y, self.w, self.z) }
    var xyww: Self { return Self(self.x, self.y, self.w, self.w) }
    var xxyy: Self { return Self(self.x, self.x, self.y, self.y) }
    var xxyx: Self { return Self(self.x, self.x, self.y, self.x) }
    var xxyz: Self { return Self(self.x, self.x, self.y, self.z) }
    var xxyw: Self { return Self(self.x, self.x, self.y, self.w) }
    var xxxy: Self { return Self(self.x, self.x, self.x, self.y) }
    var xxxx: Self { return Self(self.x, self.x, self.x, self.x) }
    var xxxz: Self { return Self(self.x, self.x, self.x, self.z) }
    var xxxw: Self { return Self(self.x, self.x, self.x, self.w) }
    var xxzy: Self { return Self(self.x, self.x, self.z, self.y) }
    var xxzx: Self { return Self(self.x, self.x, self.z, self.x) }
    var xxzz: Self { return Self(self.x, self.x, self.z, self.z) }
    var xxzw: Self { return Self(self.x, self.x, self.z, self.w) }
    var xxwy: Self { return Self(self.x, self.x, self.w, self.y) }
    var xxwx: Self { return Self(self.x, self.x, self.w, self.x) }
    var xxwz: Self { return Self(self.x, self.x, self.w, self.z) }
    var xxww: Self { return Self(self.x, self.x, self.w, self.w) }
    var xzyy: Self { return Self(self.x, self.z, self.y, self.y) }
    var xzyx: Self { return Self(self.x, self.z, self.y, self.x) }
    var xzyz: Self { return Self(self.x, self.z, self.y, self.z) }
    var xzyw: Self { return Self(self.x, self.z, self.y, self.w) }
    var xzxy: Self { return Self(self.x, self.z, self.x, self.y) }
    var xzxx: Self { return Self(self.x, self.z, self.x, self.x) }
    var xzxz: Self { return Self(self.x, self.z, self.x, self.z) }
    var xzxw: Self { return Self(self.x, self.z, self.x, self.w) }
    var xzzy: Self { return Self(self.x, self.z, self.z, self.y) }
    var xzzx: Self { return Self(self.x, self.z, self.z, self.x) }
    var xzzz: Self { return Self(self.x, self.z, self.z, self.z) }
    var xzzw: Self { return Self(self.x, self.z, self.z, self.w) }
    var xzwy: Self { return Self(self.x, self.z, self.w, self.y) }
    var xzwx: Self { return Self(self.x, self.z, self.w, self.x) }
    var xzwz: Self { return Self(self.x, self.z, self.w, self.z) }
    var xzww: Self { return Self(self.x, self.z, self.w, self.w) }
    var xwyy: Self { return Self(self.x, self.w, self.y, self.y) }
    var xwyx: Self { return Self(self.x, self.w, self.y, self.x) }
    var xwyz: Self { return Self(self.x, self.w, self.y, self.z) }
    var xwyw: Self { return Self(self.x, self.w, self.y, self.w) }
    var xwxy: Self { return Self(self.x, self.w, self.x, self.y) }
    var xwxx: Self { return Self(self.x, self.w, self.x, self.x) }
    var xwxz: Self { return Self(self.x, self.w, self.x, self.z) }
    var xwxw: Self { return Self(self.x, self.w, self.x, self.w) }
    var xwzy: Self { return Self(self.x, self.w, self.z, self.y) }
    var xwzx: Self { return Self(self.x, self.w, self.z, self.x) }
    var xwzz: Self { return Self(self.x, self.w, self.z, self.z) }
    var xwzw: Self { return Self(self.x, self.w, self.z, self.w) }
    var xwwy: Self { return Self(self.x, self.w, self.w, self.y) }
    var xwwx: Self { return Self(self.x, self.w, self.w, self.x) }
    var xwwz: Self { return Self(self.x, self.w, self.w, self.z) }
    var xwww: Self { return Self(self.x, self.w, self.w, self.w) }
    var zyyy: Self { return Self(self.z, self.y, self.y, self.y) }
    var zyyx: Self { return Self(self.z, self.y, self.y, self.x) }
    var zyyz: Self { return Self(self.z, self.y, self.y, self.z) }
    var zyyw: Self { return Self(self.z, self.y, self.y, self.w) }
    var zyxy: Self { return Self(self.z, self.y, self.x, self.y) }
    var zyxx: Self { return Self(self.z, self.y, self.x, self.x) }
    var zyxz: Self { return Self(self.z, self.y, self.x, self.z) }
    var zyxw: Self { return Self(self.z, self.y, self.x, self.w) }
    var zyzy: Self { return Self(self.z, self.y, self.z, self.y) }
    var zyzx: Self { return Self(self.z, self.y, self.z, self.x) }
    var zyzz: Self { return Self(self.z, self.y, self.z, self.z) }
    var zyzw: Self { return Self(self.z, self.y, self.z, self.w) }
    var zywy: Self { return Self(self.z, self.y, self.w, self.y) }
    var zywx: Self { return Self(self.z, self.y, self.w, self.x) }
    var zywz: Self { return Self(self.z, self.y, self.w, self.z) }
    var zyww: Self { return Self(self.z, self.y, self.w, self.w) }
    var zxyy: Self { return Self(self.z, self.x, self.y, self.y) }
    var zxyx: Self { return Self(self.z, self.x, self.y, self.x) }
    var zxyz: Self { return Self(self.z, self.x, self.y, self.z) }
    var zxyw: Self { return Self(self.z, self.x, self.y, self.w) }
    var zxxy: Self { return Self(self.z, self.x, self.x, self.y) }
    var zxxx: Self { return Self(self.z, self.x, self.x, self.x) }
    var zxxz: Self { return Self(self.z, self.x, self.x, self.z) }
    var zxxw: Self { return Self(self.z, self.x, self.x, self.w) }
    var zxzy: Self { return Self(self.z, self.x, self.z, self.y) }
    var zxzx: Self { return Self(self.z, self.x, self.z, self.x) }
    var zxzz: Self { return Self(self.z, self.x, self.z, self.z) }
    var zxzw: Self { return Self(self.z, self.x, self.z, self.w) }
    var zxwy: Self { return Self(self.z, self.x, self.w, self.y) }
    var zxwx: Self { return Self(self.z, self.x, self.w, self.x) }
    var zxwz: Self { return Self(self.z, self.x, self.w, self.z) }
    var zxww: Self { return Self(self.z, self.x, self.w, self.w) }
    var zzyy: Self { return Self(self.z, self.z, self.y, self.y) }
    var zzyx: Self { return Self(self.z, self.z, self.y, self.x) }
    var zzyz: Self { return Self(self.z, self.z, self.y, self.z) }
    var zzyw: Self { return Self(self.z, self.z, self.y, self.w) }
    var zzxy: Self { return Self(self.z, self.z, self.x, self.y) }
    var zzxx: Self { return Self(self.z, self.z, self.x, self.x) }
    var zzxz: Self { return Self(self.z, self.z, self.x, self.z) }
    var zzxw: Self { return Self(self.z, self.z, self.x, self.w) }
    var zzzy: Self { return Self(self.z, self.z, self.z, self.y) }
    var zzzx: Self { return Self(self.z, self.z, self.z, self.x) }
    var zzzz: Self { return Self(self.z, self.z, self.z, self.z) }
    var zzzw: Self { return Self(self.z, self.z, self.z, self.w) }
    var zzwy: Self { return Self(self.z, self.z, self.w, self.y) }
    var zzwx: Self { return Self(self.z, self.z, self.w, self.x) }
    var zzwz: Self { return Self(self.z, self.z, self.w, self.z) }
    var zzww: Self { return Self(self.z, self.z, self.w, self.w) }
    var zwyy: Self { return Self(self.z, self.w, self.y, self.y) }
    var zwyx: Self { return Self(self.z, self.w, self.y, self.x) }
    var zwyz: Self { return Self(self.z, self.w, self.y, self.z) }
    var zwyw: Self { return Self(self.z, self.w, self.y, self.w) }
    var zwxy: Self { return Self(self.z, self.w, self.x, self.y) }
    var zwxx: Self { return Self(self.z, self.w, self.x, self.x) }
    var zwxz: Self { return Self(self.z, self.w, self.x, self.z) }
    var zwxw: Self { return Self(self.z, self.w, self.x, self.w) }
    var zwzy: Self { return Self(self.z, self.w, self.z, self.y) }
    var zwzx: Self { return Self(self.z, self.w, self.z, self.x) }
    var zwzz: Self { return Self(self.z, self.w, self.z, self.z) }
    var zwzw: Self { return Self(self.z, self.w, self.z, self.w) }
    var zwwy: Self { return Self(self.z, self.w, self.w, self.y) }
    var zwwx: Self { return Self(self.z, self.w, self.w, self.x) }
    var zwwz: Self { return Self(self.z, self.w, self.w, self.z) }
    var zwww: Self { return Self(self.z, self.w, self.w, self.w) }
    var wyyy: Self { return Self(self.w, self.y, self.y, self.y) }
    var wyyx: Self { return Self(self.w, self.y, self.y, self.x) }
    var wyyz: Self { return Self(self.w, self.y, self.y, self.z) }
    var wyyw: Self { return Self(self.w, self.y, self.y, self.w) }
    var wyxy: Self { return Self(self.w, self.y, self.x, self.y) }
    var wyxx: Self { return Self(self.w, self.y, self.x, self.x) }
    var wyxz: Self { return Self(self.w, self.y, self.x, self.z) }
    var wyxw: Self { return Self(self.w, self.y, self.x, self.w) }
    var wyzy: Self { return Self(self.w, self.y, self.z, self.y) }
    var wyzx: Self { return Self(self.w, self.y, self.z, self.x) }
    var wyzz: Self { return Self(self.w, self.y, self.z, self.z) }
    var wyzw: Self { return Self(self.w, self.y, self.z, self.w) }
    var wywy: Self { return Self(self.w, self.y, self.w, self.y) }
    var wywx: Self { return Self(self.w, self.y, self.w, self.x) }
    var wywz: Self { return Self(self.w, self.y, self.w, self.z) }
    var wyww: Self { return Self(self.w, self.y, self.w, self.w) }
    var wxyy: Self { return Self(self.w, self.x, self.y, self.y) }
    var wxyx: Self { return Self(self.w, self.x, self.y, self.x) }
    var wxyz: Self { return Self(self.w, self.x, self.y, self.z) }
    var wxyw: Self { return Self(self.w, self.x, self.y, self.w) }
    var wxxy: Self { return Self(self.w, self.x, self.x, self.y) }
    var wxxx: Self { return Self(self.w, self.x, self.x, self.x) }
    var wxxz: Self { return Self(self.w, self.x, self.x, self.z) }
    var wxxw: Self { return Self(self.w, self.x, self.x, self.w) }
    var wxzy: Self { return Self(self.w, self.x, self.z, self.y) }
    var wxzx: Self { return Self(self.w, self.x, self.z, self.x) }
    var wxzz: Self { return Self(self.w, self.x, self.z, self.z) }
    var wxzw: Self { return Self(self.w, self.x, self.z, self.w) }
    var wxwy: Self { return Self(self.w, self.x, self.w, self.y) }
    var wxwx: Self { return Self(self.w, self.x, self.w, self.x) }
    var wxwz: Self { return Self(self.w, self.x, self.w, self.z) }
    var wxww: Self { return Self(self.w, self.x, self.w, self.w) }
    var wzyy: Self { return Self(self.w, self.z, self.y, self.y) }
    var wzyx: Self { return Self(self.w, self.z, self.y, self.x) }
    var wzyz: Self { return Self(self.w, self.z, self.y, self.z) }
    var wzyw: Self { return Self(self.w, self.z, self.y, self.w) }
    var wzxy: Self { return Self(self.w, self.z, self.x, self.y) }
    var wzxx: Self { return Self(self.w, self.z, self.x, self.x) }
    var wzxz: Self { return Self(self.w, self.z, self.x, self.z) }
    var wzxw: Self { return Self(self.w, self.z, self.x, self.w) }
    var wzzy: Self { return Self(self.w, self.z, self.z, self.y) }
    var wzzx: Self { return Self(self.w, self.z, self.z, self.x) }
    var wzzz: Self { return Self(self.w, self.z, self.z, self.z) }
    var wzzw: Self { return Self(self.w, self.z, self.z, self.w) }
    var wzwy: Self { return Self(self.w, self.z, self.w, self.y) }
    var wzwx: Self { return Self(self.w, self.z, self.w, self.x) }
    var wzwz: Self { return Self(self.w, self.z, self.w, self.z) }
    var wzww: Self { return Self(self.w, self.z, self.w, self.w) }
    var wwyy: Self { return Self(self.w, self.w, self.y, self.y) }
    var wwyx: Self { return Self(self.w, self.w, self.y, self.x) }
    var wwyz: Self { return Self(self.w, self.w, self.y, self.z) }
    var wwyw: Self { return Self(self.w, self.w, self.y, self.w) }
    var wwxy: Self { return Self(self.w, self.w, self.x, self.y) }
    var wwxx: Self { return Self(self.w, self.w, self.x, self.x) }
    var wwxz: Self { return Self(self.w, self.w, self.x, self.z) }
    var wwxw: Self { return Self(self.w, self.w, self.x, self.w) }
    var wwzy: Self { return Self(self.w, self.w, self.z, self.y) }
    var wwzx: Self { return Self(self.w, self.w, self.z, self.x) }
    var wwzz: Self { return Self(self.w, self.w, self.z, self.z) }
    var wwzw: Self { return Self(self.w, self.w, self.z, self.w) }
    var wwwy: Self { return Self(self.w, self.w, self.w, self.y) }
    var wwwx: Self { return Self(self.w, self.w, self.w, self.x) }
    var wwwz: Self { return Self(self.w, self.w, self.w, self.z) }
    var wwww: Self { return Self(self.w, self.w, self.w, self.w) }
    var aa: AssociatedVector2 { return AssociatedVector2(self.a, self.a) }
    var ar: AssociatedVector2 { return AssociatedVector2(self.a, self.r) }
    var ab: AssociatedVector2 { return AssociatedVector2(self.a, self.b) }
    var ag: AssociatedVector2 { return AssociatedVector2(self.a, self.g) }
    var ra: AssociatedVector2 { return AssociatedVector2(self.r, self.a) }
    var rr: AssociatedVector2 { return AssociatedVector2(self.r, self.r) }
    var rb: AssociatedVector2 { return AssociatedVector2(self.r, self.b) }
    var rg: AssociatedVector2 { return AssociatedVector2(self.r, self.g) }
    var ba: AssociatedVector2 { return AssociatedVector2(self.b, self.a) }
    var br: AssociatedVector2 { return AssociatedVector2(self.b, self.r) }
    var bb: AssociatedVector2 { return AssociatedVector2(self.b, self.b) }
    var bg: AssociatedVector2 { return AssociatedVector2(self.b, self.g) }
    var ga: AssociatedVector2 { return AssociatedVector2(self.g, self.a) }
    var gr: AssociatedVector2 { return AssociatedVector2(self.g, self.r) }
    var gb: AssociatedVector2 { return AssociatedVector2(self.g, self.b) }
    var gg: AssociatedVector2 { return AssociatedVector2(self.g, self.g) }
    var aaa: AssociatedVector3 { return AssociatedVector3(self.a, self.a, self.a) }
    var aar: AssociatedVector3 { return AssociatedVector3(self.a, self.a, self.r) }
    var aab: AssociatedVector3 { return AssociatedVector3(self.a, self.a, self.b) }
    var aag: AssociatedVector3 { return AssociatedVector3(self.a, self.a, self.g) }
    var ara: AssociatedVector3 { return AssociatedVector3(self.a, self.r, self.a) }
    var arr: AssociatedVector3 { return AssociatedVector3(self.a, self.r, self.r) }
    var arb: AssociatedVector3 { return AssociatedVector3(self.a, self.r, self.b) }
    var arg: AssociatedVector3 { return AssociatedVector3(self.a, self.r, self.g) }
    var aba: AssociatedVector3 { return AssociatedVector3(self.a, self.b, self.a) }
    var abr: AssociatedVector3 { return AssociatedVector3(self.a, self.b, self.r) }
    var abb: AssociatedVector3 { return AssociatedVector3(self.a, self.b, self.b) }
    var abg: AssociatedVector3 { return AssociatedVector3(self.a, self.b, self.g) }
    var aga: AssociatedVector3 { return AssociatedVector3(self.a, self.g, self.a) }
    var agr: AssociatedVector3 { return AssociatedVector3(self.a, self.g, self.r) }
    var agb: AssociatedVector3 { return AssociatedVector3(self.a, self.g, self.b) }
    var agg: AssociatedVector3 { return AssociatedVector3(self.a, self.g, self.g) }
    var raa: AssociatedVector3 { return AssociatedVector3(self.r, self.a, self.a) }
    var rar: AssociatedVector3 { return AssociatedVector3(self.r, self.a, self.r) }
    var rab: AssociatedVector3 { return AssociatedVector3(self.r, self.a, self.b) }
    var rag: AssociatedVector3 { return AssociatedVector3(self.r, self.a, self.g) }
    var rra: AssociatedVector3 { return AssociatedVector3(self.r, self.r, self.a) }
    var rrr: AssociatedVector3 { return AssociatedVector3(self.r, self.r, self.r) }
    var rrb: AssociatedVector3 { return AssociatedVector3(self.r, self.r, self.b) }
    var rrg: AssociatedVector3 { return AssociatedVector3(self.r, self.r, self.g) }
    var rba: AssociatedVector3 { return AssociatedVector3(self.r, self.b, self.a) }
    var rbr: AssociatedVector3 { return AssociatedVector3(self.r, self.b, self.r) }
    var rbb: AssociatedVector3 { return AssociatedVector3(self.r, self.b, self.b) }
    var rbg: AssociatedVector3 { return AssociatedVector3(self.r, self.b, self.g) }
    var rga: AssociatedVector3 { return AssociatedVector3(self.r, self.g, self.a) }
    var rgr: AssociatedVector3 { return AssociatedVector3(self.r, self.g, self.r) }
    var rgb: AssociatedVector3 { return AssociatedVector3(self.r, self.g, self.b) }
    var rgg: AssociatedVector3 { return AssociatedVector3(self.r, self.g, self.g) }
    var baa: AssociatedVector3 { return AssociatedVector3(self.b, self.a, self.a) }
    var bar: AssociatedVector3 { return AssociatedVector3(self.b, self.a, self.r) }
    var bab: AssociatedVector3 { return AssociatedVector3(self.b, self.a, self.b) }
    var bag: AssociatedVector3 { return AssociatedVector3(self.b, self.a, self.g) }
    var bra: AssociatedVector3 { return AssociatedVector3(self.b, self.r, self.a) }
    var brr: AssociatedVector3 { return AssociatedVector3(self.b, self.r, self.r) }
    var brb: AssociatedVector3 { return AssociatedVector3(self.b, self.r, self.b) }
    var brg: AssociatedVector3 { return AssociatedVector3(self.b, self.r, self.g) }
    var bba: AssociatedVector3 { return AssociatedVector3(self.b, self.b, self.a) }
    var bbr: AssociatedVector3 { return AssociatedVector3(self.b, self.b, self.r) }
    var bbb: AssociatedVector3 { return AssociatedVector3(self.b, self.b, self.b) }
    var bbg: AssociatedVector3 { return AssociatedVector3(self.b, self.b, self.g) }
    var bga: AssociatedVector3 { return AssociatedVector3(self.b, self.g, self.a) }
    var bgr: AssociatedVector3 { return AssociatedVector3(self.b, self.g, self.r) }
    var bgb: AssociatedVector3 { return AssociatedVector3(self.b, self.g, self.b) }
    var bgg: AssociatedVector3 { return AssociatedVector3(self.b, self.g, self.g) }
    var gaa: AssociatedVector3 { return AssociatedVector3(self.g, self.a, self.a) }
    var gar: AssociatedVector3 { return AssociatedVector3(self.g, self.a, self.r) }
    var gab: AssociatedVector3 { return AssociatedVector3(self.g, self.a, self.b) }
    var gag: AssociatedVector3 { return AssociatedVector3(self.g, self.a, self.g) }
    var gra: AssociatedVector3 { return AssociatedVector3(self.g, self.r, self.a) }
    var grr: AssociatedVector3 { return AssociatedVector3(self.g, self.r, self.r) }
    var grb: AssociatedVector3 { return AssociatedVector3(self.g, self.r, self.b) }
    var grg: AssociatedVector3 { return AssociatedVector3(self.g, self.r, self.g) }
    var gba: AssociatedVector3 { return AssociatedVector3(self.g, self.b, self.a) }
    var gbr: AssociatedVector3 { return AssociatedVector3(self.g, self.b, self.r) }
    var gbb: AssociatedVector3 { return AssociatedVector3(self.g, self.b, self.b) }
    var gbg: AssociatedVector3 { return AssociatedVector3(self.g, self.b, self.g) }
    var gga: AssociatedVector3 { return AssociatedVector3(self.g, self.g, self.a) }
    var ggr: AssociatedVector3 { return AssociatedVector3(self.g, self.g, self.r) }
    var ggb: AssociatedVector3 { return AssociatedVector3(self.g, self.g, self.b) }
    var ggg: AssociatedVector3 { return AssociatedVector3(self.g, self.g, self.g) }
    var aaaa: Self { return Self(self.a, self.a, self.a, self.a) }
    var aaar: Self { return Self(self.a, self.a, self.a, self.r) }
    var aaab: Self { return Self(self.a, self.a, self.a, self.b) }
    var aaag: Self { return Self(self.a, self.a, self.a, self.g) }
    var aara: Self { return Self(self.a, self.a, self.r, self.a) }
    var aarr: Self { return Self(self.a, self.a, self.r, self.r) }
    var aarb: Self { return Self(self.a, self.a, self.r, self.b) }
    var aarg: Self { return Self(self.a, self.a, self.r, self.g) }
    var aaba: Self { return Self(self.a, self.a, self.b, self.a) }
    var aabr: Self { return Self(self.a, self.a, self.b, self.r) }
    var aabb: Self { return Self(self.a, self.a, self.b, self.b) }
    var aabg: Self { return Self(self.a, self.a, self.b, self.g) }
    var aaga: Self { return Self(self.a, self.a, self.g, self.a) }
    var aagr: Self { return Self(self.a, self.a, self.g, self.r) }
    var aagb: Self { return Self(self.a, self.a, self.g, self.b) }
    var aagg: Self { return Self(self.a, self.a, self.g, self.g) }
    var araa: Self { return Self(self.a, self.r, self.a, self.a) }
    var arar: Self { return Self(self.a, self.r, self.a, self.r) }
    var arab: Self { return Self(self.a, self.r, self.a, self.b) }
    var arag: Self { return Self(self.a, self.r, self.a, self.g) }
    var arra: Self { return Self(self.a, self.r, self.r, self.a) }
    var arrr: Self { return Self(self.a, self.r, self.r, self.r) }
    var arrb: Self { return Self(self.a, self.r, self.r, self.b) }
    var arrg: Self { return Self(self.a, self.r, self.r, self.g) }
    var arba: Self { return Self(self.a, self.r, self.b, self.a) }
    var arbr: Self { return Self(self.a, self.r, self.b, self.r) }
    var arbb: Self { return Self(self.a, self.r, self.b, self.b) }
    var arbg: Self { return Self(self.a, self.r, self.b, self.g) }
    var arga: Self { return Self(self.a, self.r, self.g, self.a) }
    var argr: Self { return Self(self.a, self.r, self.g, self.r) }
    var argb: Self { return Self(self.a, self.r, self.g, self.b) }
    var argg: Self { return Self(self.a, self.r, self.g, self.g) }
    var abaa: Self { return Self(self.a, self.b, self.a, self.a) }
    var abar: Self { return Self(self.a, self.b, self.a, self.r) }
    var abab: Self { return Self(self.a, self.b, self.a, self.b) }
    var abag: Self { return Self(self.a, self.b, self.a, self.g) }
    var abra: Self { return Self(self.a, self.b, self.r, self.a) }
    var abrr: Self { return Self(self.a, self.b, self.r, self.r) }
    var abrb: Self { return Self(self.a, self.b, self.r, self.b) }
    var abrg: Self { return Self(self.a, self.b, self.r, self.g) }
    var abba: Self { return Self(self.a, self.b, self.b, self.a) }
    var abbr: Self { return Self(self.a, self.b, self.b, self.r) }
    var abbb: Self { return Self(self.a, self.b, self.b, self.b) }
    var abbg: Self { return Self(self.a, self.b, self.b, self.g) }
    var abga: Self { return Self(self.a, self.b, self.g, self.a) }
    var abgr: Self { return Self(self.a, self.b, self.g, self.r) }
    var abgb: Self { return Self(self.a, self.b, self.g, self.b) }
    var abgg: Self { return Self(self.a, self.b, self.g, self.g) }
    var agaa: Self { return Self(self.a, self.g, self.a, self.a) }
    var agar: Self { return Self(self.a, self.g, self.a, self.r) }
    var agab: Self { return Self(self.a, self.g, self.a, self.b) }
    var agag: Self { return Self(self.a, self.g, self.a, self.g) }
    var agra: Self { return Self(self.a, self.g, self.r, self.a) }
    var agrr: Self { return Self(self.a, self.g, self.r, self.r) }
    var agrb: Self { return Self(self.a, self.g, self.r, self.b) }
    var agrg: Self { return Self(self.a, self.g, self.r, self.g) }
    var agba: Self { return Self(self.a, self.g, self.b, self.a) }
    var agbr: Self { return Self(self.a, self.g, self.b, self.r) }
    var agbb: Self { return Self(self.a, self.g, self.b, self.b) }
    var agbg: Self { return Self(self.a, self.g, self.b, self.g) }
    var agga: Self { return Self(self.a, self.g, self.g, self.a) }
    var aggr: Self { return Self(self.a, self.g, self.g, self.r) }
    var aggb: Self { return Self(self.a, self.g, self.g, self.b) }
    var aggg: Self { return Self(self.a, self.g, self.g, self.g) }
    var raaa: Self { return Self(self.r, self.a, self.a, self.a) }
    var raar: Self { return Self(self.r, self.a, self.a, self.r) }
    var raab: Self { return Self(self.r, self.a, self.a, self.b) }
    var raag: Self { return Self(self.r, self.a, self.a, self.g) }
    var rara: Self { return Self(self.r, self.a, self.r, self.a) }
    var rarr: Self { return Self(self.r, self.a, self.r, self.r) }
    var rarb: Self { return Self(self.r, self.a, self.r, self.b) }
    var rarg: Self { return Self(self.r, self.a, self.r, self.g) }
    var raba: Self { return Self(self.r, self.a, self.b, self.a) }
    var rabr: Self { return Self(self.r, self.a, self.b, self.r) }
    var rabb: Self { return Self(self.r, self.a, self.b, self.b) }
    var rabg: Self { return Self(self.r, self.a, self.b, self.g) }
    var raga: Self { return Self(self.r, self.a, self.g, self.a) }
    var ragr: Self { return Self(self.r, self.a, self.g, self.r) }
    var ragb: Self { return Self(self.r, self.a, self.g, self.b) }
    var ragg: Self { return Self(self.r, self.a, self.g, self.g) }
    var rraa: Self { return Self(self.r, self.r, self.a, self.a) }
    var rrar: Self { return Self(self.r, self.r, self.a, self.r) }
    var rrab: Self { return Self(self.r, self.r, self.a, self.b) }
    var rrag: Self { return Self(self.r, self.r, self.a, self.g) }
    var rrra: Self { return Self(self.r, self.r, self.r, self.a) }
    var rrrr: Self { return Self(self.r, self.r, self.r, self.r) }
    var rrrb: Self { return Self(self.r, self.r, self.r, self.b) }
    var rrrg: Self { return Self(self.r, self.r, self.r, self.g) }
    var rrba: Self { return Self(self.r, self.r, self.b, self.a) }
    var rrbr: Self { return Self(self.r, self.r, self.b, self.r) }
    var rrbb: Self { return Self(self.r, self.r, self.b, self.b) }
    var rrbg: Self { return Self(self.r, self.r, self.b, self.g) }
    var rrga: Self { return Self(self.r, self.r, self.g, self.a) }
    var rrgr: Self { return Self(self.r, self.r, self.g, self.r) }
    var rrgb: Self { return Self(self.r, self.r, self.g, self.b) }
    var rrgg: Self { return Self(self.r, self.r, self.g, self.g) }
    var rbaa: Self { return Self(self.r, self.b, self.a, self.a) }
    var rbar: Self { return Self(self.r, self.b, self.a, self.r) }
    var rbab: Self { return Self(self.r, self.b, self.a, self.b) }
    var rbag: Self { return Self(self.r, self.b, self.a, self.g) }
    var rbra: Self { return Self(self.r, self.b, self.r, self.a) }
    var rbrr: Self { return Self(self.r, self.b, self.r, self.r) }
    var rbrb: Self { return Self(self.r, self.b, self.r, self.b) }
    var rbrg: Self { return Self(self.r, self.b, self.r, self.g) }
    var rbba: Self { return Self(self.r, self.b, self.b, self.a) }
    var rbbr: Self { return Self(self.r, self.b, self.b, self.r) }
    var rbbb: Self { return Self(self.r, self.b, self.b, self.b) }
    var rbbg: Self { return Self(self.r, self.b, self.b, self.g) }
    var rbga: Self { return Self(self.r, self.b, self.g, self.a) }
    var rbgr: Self { return Self(self.r, self.b, self.g, self.r) }
    var rbgb: Self { return Self(self.r, self.b, self.g, self.b) }
    var rbgg: Self { return Self(self.r, self.b, self.g, self.g) }
    var rgaa: Self { return Self(self.r, self.g, self.a, self.a) }
    var rgar: Self { return Self(self.r, self.g, self.a, self.r) }
    var rgab: Self { return Self(self.r, self.g, self.a, self.b) }
    var rgag: Self { return Self(self.r, self.g, self.a, self.g) }
    var rgra: Self { return Self(self.r, self.g, self.r, self.a) }
    var rgrr: Self { return Self(self.r, self.g, self.r, self.r) }
    var rgrb: Self { return Self(self.r, self.g, self.r, self.b) }
    var rgrg: Self { return Self(self.r, self.g, self.r, self.g) }
    var rgba: Self { return Self(self.r, self.g, self.b, self.a) }
    var rgbr: Self { return Self(self.r, self.g, self.b, self.r) }
    var rgbb: Self { return Self(self.r, self.g, self.b, self.b) }
    var rgbg: Self { return Self(self.r, self.g, self.b, self.g) }
    var rgga: Self { return Self(self.r, self.g, self.g, self.a) }
    var rggr: Self { return Self(self.r, self.g, self.g, self.r) }
    var rggb: Self { return Self(self.r, self.g, self.g, self.b) }
    var rggg: Self { return Self(self.r, self.g, self.g, self.g) }
    var baaa: Self { return Self(self.b, self.a, self.a, self.a) }
    var baar: Self { return Self(self.b, self.a, self.a, self.r) }
    var baab: Self { return Self(self.b, self.a, self.a, self.b) }
    var baag: Self { return Self(self.b, self.a, self.a, self.g) }
    var bara: Self { return Self(self.b, self.a, self.r, self.a) }
    var barr: Self { return Self(self.b, self.a, self.r, self.r) }
    var barb: Self { return Self(self.b, self.a, self.r, self.b) }
    var barg: Self { return Self(self.b, self.a, self.r, self.g) }
    var baba: Self { return Self(self.b, self.a, self.b, self.a) }
    var babr: Self { return Self(self.b, self.a, self.b, self.r) }
    var babb: Self { return Self(self.b, self.a, self.b, self.b) }
    var babg: Self { return Self(self.b, self.a, self.b, self.g) }
    var baga: Self { return Self(self.b, self.a, self.g, self.a) }
    var bagr: Self { return Self(self.b, self.a, self.g, self.r) }
    var bagb: Self { return Self(self.b, self.a, self.g, self.b) }
    var bagg: Self { return Self(self.b, self.a, self.g, self.g) }
    var braa: Self { return Self(self.b, self.r, self.a, self.a) }
    var brar: Self { return Self(self.b, self.r, self.a, self.r) }
    var brab: Self { return Self(self.b, self.r, self.a, self.b) }
    var brag: Self { return Self(self.b, self.r, self.a, self.g) }
    var brra: Self { return Self(self.b, self.r, self.r, self.a) }
    var brrr: Self { return Self(self.b, self.r, self.r, self.r) }
    var brrb: Self { return Self(self.b, self.r, self.r, self.b) }
    var brrg: Self { return Self(self.b, self.r, self.r, self.g) }
    var brba: Self { return Self(self.b, self.r, self.b, self.a) }
    var brbr: Self { return Self(self.b, self.r, self.b, self.r) }
    var brbb: Self { return Self(self.b, self.r, self.b, self.b) }
    var brbg: Self { return Self(self.b, self.r, self.b, self.g) }
    var brga: Self { return Self(self.b, self.r, self.g, self.a) }
    var brgr: Self { return Self(self.b, self.r, self.g, self.r) }
    var brgb: Self { return Self(self.b, self.r, self.g, self.b) }
    var brgg: Self { return Self(self.b, self.r, self.g, self.g) }
    var bbaa: Self { return Self(self.b, self.b, self.a, self.a) }
    var bbar: Self { return Self(self.b, self.b, self.a, self.r) }
    var bbab: Self { return Self(self.b, self.b, self.a, self.b) }
    var bbag: Self { return Self(self.b, self.b, self.a, self.g) }
    var bbra: Self { return Self(self.b, self.b, self.r, self.a) }
    var bbrr: Self { return Self(self.b, self.b, self.r, self.r) }
    var bbrb: Self { return Self(self.b, self.b, self.r, self.b) }
    var bbrg: Self { return Self(self.b, self.b, self.r, self.g) }
    var bbba: Self { return Self(self.b, self.b, self.b, self.a) }
    var bbbr: Self { return Self(self.b, self.b, self.b, self.r) }
    var bbbb: Self { return Self(self.b, self.b, self.b, self.b) }
    var bbbg: Self { return Self(self.b, self.b, self.b, self.g) }
    var bbga: Self { return Self(self.b, self.b, self.g, self.a) }
    var bbgr: Self { return Self(self.b, self.b, self.g, self.r) }
    var bbgb: Self { return Self(self.b, self.b, self.g, self.b) }
    var bbgg: Self { return Self(self.b, self.b, self.g, self.g) }
    var bgaa: Self { return Self(self.b, self.g, self.a, self.a) }
    var bgar: Self { return Self(self.b, self.g, self.a, self.r) }
    var bgab: Self { return Self(self.b, self.g, self.a, self.b) }
    var bgag: Self { return Self(self.b, self.g, self.a, self.g) }
    var bgra: Self { return Self(self.b, self.g, self.r, self.a) }
    var bgrr: Self { return Self(self.b, self.g, self.r, self.r) }
    var bgrb: Self { return Self(self.b, self.g, self.r, self.b) }
    var bgrg: Self { return Self(self.b, self.g, self.r, self.g) }
    var bgba: Self { return Self(self.b, self.g, self.b, self.a) }
    var bgbr: Self { return Self(self.b, self.g, self.b, self.r) }
    var bgbb: Self { return Self(self.b, self.g, self.b, self.b) }
    var bgbg: Self { return Self(self.b, self.g, self.b, self.g) }
    var bgga: Self { return Self(self.b, self.g, self.g, self.a) }
    var bggr: Self { return Self(self.b, self.g, self.g, self.r) }
    var bggb: Self { return Self(self.b, self.g, self.g, self.b) }
    var bggg: Self { return Self(self.b, self.g, self.g, self.g) }
    var gaaa: Self { return Self(self.g, self.a, self.a, self.a) }
    var gaar: Self { return Self(self.g, self.a, self.a, self.r) }
    var gaab: Self { return Self(self.g, self.a, self.a, self.b) }
    var gaag: Self { return Self(self.g, self.a, self.a, self.g) }
    var gara: Self { return Self(self.g, self.a, self.r, self.a) }
    var garr: Self { return Self(self.g, self.a, self.r, self.r) }
    var garb: Self { return Self(self.g, self.a, self.r, self.b) }
    var garg: Self { return Self(self.g, self.a, self.r, self.g) }
    var gaba: Self { return Self(self.g, self.a, self.b, self.a) }
    var gabr: Self { return Self(self.g, self.a, self.b, self.r) }
    var gabb: Self { return Self(self.g, self.a, self.b, self.b) }
    var gabg: Self { return Self(self.g, self.a, self.b, self.g) }
    var gaga: Self { return Self(self.g, self.a, self.g, self.a) }
    var gagr: Self { return Self(self.g, self.a, self.g, self.r) }
    var gagb: Self { return Self(self.g, self.a, self.g, self.b) }
    var gagg: Self { return Self(self.g, self.a, self.g, self.g) }
    var graa: Self { return Self(self.g, self.r, self.a, self.a) }
    var grar: Self { return Self(self.g, self.r, self.a, self.r) }
    var grab: Self { return Self(self.g, self.r, self.a, self.b) }
    var grag: Self { return Self(self.g, self.r, self.a, self.g) }
    var grra: Self { return Self(self.g, self.r, self.r, self.a) }
    var grrr: Self { return Self(self.g, self.r, self.r, self.r) }
    var grrb: Self { return Self(self.g, self.r, self.r, self.b) }
    var grrg: Self { return Self(self.g, self.r, self.r, self.g) }
    var grba: Self { return Self(self.g, self.r, self.b, self.a) }
    var grbr: Self { return Self(self.g, self.r, self.b, self.r) }
    var grbb: Self { return Self(self.g, self.r, self.b, self.b) }
    var grbg: Self { return Self(self.g, self.r, self.b, self.g) }
    var grga: Self { return Self(self.g, self.r, self.g, self.a) }
    var grgr: Self { return Self(self.g, self.r, self.g, self.r) }
    var grgb: Self { return Self(self.g, self.r, self.g, self.b) }
    var grgg: Self { return Self(self.g, self.r, self.g, self.g) }
    var gbaa: Self { return Self(self.g, self.b, self.a, self.a) }
    var gbar: Self { return Self(self.g, self.b, self.a, self.r) }
    var gbab: Self { return Self(self.g, self.b, self.a, self.b) }
    var gbag: Self { return Self(self.g, self.b, self.a, self.g) }
    var gbra: Self { return Self(self.g, self.b, self.r, self.a) }
    var gbrr: Self { return Self(self.g, self.b, self.r, self.r) }
    var gbrb: Self { return Self(self.g, self.b, self.r, self.b) }
    var gbrg: Self { return Self(self.g, self.b, self.r, self.g) }
    var gbba: Self { return Self(self.g, self.b, self.b, self.a) }
    var gbbr: Self { return Self(self.g, self.b, self.b, self.r) }
    var gbbb: Self { return Self(self.g, self.b, self.b, self.b) }
    var gbbg: Self { return Self(self.g, self.b, self.b, self.g) }
    var gbga: Self { return Self(self.g, self.b, self.g, self.a) }
    var gbgr: Self { return Self(self.g, self.b, self.g, self.r) }
    var gbgb: Self { return Self(self.g, self.b, self.g, self.b) }
    var gbgg: Self { return Self(self.g, self.b, self.g, self.g) }
    var ggaa: Self { return Self(self.g, self.g, self.a, self.a) }
    var ggar: Self { return Self(self.g, self.g, self.a, self.r) }
    var ggab: Self { return Self(self.g, self.g, self.a, self.b) }
    var ggag: Self { return Self(self.g, self.g, self.a, self.g) }
    var ggra: Self { return Self(self.g, self.g, self.r, self.a) }
    var ggrr: Self { return Self(self.g, self.g, self.r, self.r) }
    var ggrb: Self { return Self(self.g, self.g, self.r, self.b) }
    var ggrg: Self { return Self(self.g, self.g, self.r, self.g) }
    var ggba: Self { return Self(self.g, self.g, self.b, self.a) }
    var ggbr: Self { return Self(self.g, self.g, self.b, self.r) }
    var ggbb: Self { return Self(self.g, self.g, self.b, self.b) }
    var ggbg: Self { return Self(self.g, self.g, self.b, self.g) }
    var ggga: Self { return Self(self.g, self.g, self.g, self.a) }
    var gggr: Self { return Self(self.g, self.g, self.g, self.r) }
    var gggb: Self { return Self(self.g, self.g, self.g, self.b) }
    var gggg: Self { return Self(self.g, self.g, self.g, self.g) }
}
